### ISSUE TITLE
Py3: TypeError on call of scipy.stats._binned_statistics

### ISSUE THREAD

**Issue by owtscharenko** [SiLab-Bonn/beam_telescope_analysis#11]
With python 3.7 scipys binned statistics has change behavior
In **result_analysis.py L. 261** binned_statistics is called with `values = None` causing a TypeError:

> TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

What is new is that values is checked with np.isfinite()
**scipy.stats._binned_statistic.py L. 518**

> if not np.isfinite(values).all() or not np.isfinite(sample).all:

this check can not be performed on None type.

**Comment by DavidLP** [comment]
Irrelevant for this bug, but cleaner is:
```python
if np.isfinite(values).any() or np.isfinite(sample).any():
```

**Comment by YannickDieter** [comment]
Not an issue anymore in the recent version of `scipy`. See [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binned_statistic_2d.html)

> ‘count’ : compute the count of points within each bin. This is identical to an unweighted histogram. values array is not referenced.
