### ISSUE TITLE
collections Iterable - ImportError

### ISSUE THREAD

**Issue by owtscharenko** [SiLab-Bonn/beam_telescope_analysis#21]
For a fresh checkout in master, running `examples/fei4_telescope.py` I get following error:

> File "/home/niko/git/beam_telescope_analysis/beam_telescope_analysis/examples/fei4_telescope.py", line 17, in <module>
    from beam_telescope_analysis import dut_alignment
  File "/home/niko/git/beam_telescope_analysis/beam_telescope_analysis/dut_alignment.py", line 7, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/home/niko/anaconda3/envs/tba_env/lib/python3.10/collections/__init__.py)

I am running on conda with python 3.10.5 

Apparently collections was changed in a recent python update, and `Iterables` has now to be imported from `collections.abc`:

https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python

**Comment by YannickDieter** [comment]
See #22 .
