### ISSUE TITLE
Unnecessary requirement

### ISSUE THREAD

**Issue by cbespin** [SiLab-Bonn/beam_telescope_analysis#24]
The `analysis_tools.py` file contains a function [`get_data()`](https://github.com/SiLab-Bonn/beam_telescope_analysis/blob/0d4f47463c1d4396375db42aa69eb565bc1c6ebf/beam_telescope_analysis/tools/analysis_utils.py#L1309) to download data from a sciebo repository, e.g for examples or unit tests.
This introduces the dependency on the `requests` package which is no needed for any normal usage, but imported and therefore required. Maybe `get_data()` should be moved to its on file under `beam_telescope_analysis/testing`?

**Comment by cbespin** [comment]
I did not install it because I thought there should be no reason to. But it is for unnecessary reasons. Not important, just something to maybe think about ;)

**Comment by leloup314** [comment]
Do we really need this? Can this not be solved via `git LFS`?

**Comment by cbespin** [comment]
I see it being used in examples (where it could be useful to get data easier than with `git LFS`) and in tests. Not sure how to solve this best

**Comment by YannickDieter** [comment]
Good idea, I will move also the test data to git-lfs.

**Comment by leloup314** [comment]
We are only using 6 of 100 GB currently, so it is worth to try :)
