### ISSUE TITLE
BUG: Wrong use of np.resize

### ISSUE THREAD

**Issue by lschall** [SiLab-Bonn/beam_telescope_analysis#28]
With commit 9e2289adb14123c3d265935436ec3c9ea110c748 a wrong use of `np.resize` was implemented. `np.resize` fills additionally added entries in the new array by repeating elements of the original one ([see here](https://numpy.org/doc/stable/reference/generated/numpy.resize.html)). This can lead to wrong histograms in the final step of the analysis. The correct way of resizing in this case is `array.resize(shape)` as this method complements the original array with zeros (if needed).

**Comment by leloup314** [comment]
Nice find!

**Comment by YannickDieter** [comment]
Thanks for finding this huge bug! I will revert the commit.

**Comment by YannickDieter** [comment]
Fixed with 7238363. I also decreased the chun ksize during unit testing ([f712492](https://github.com/SiLab-Bonn/beam_telescope_analysis/commit/f7124928b35a57676de78b2d909915fe69f75c6a)) such that this is also no covered by unit tests ;)
