### ISSUE TITLE
reduce_events() does not work on merged data file

### ISSUE THREAD

**Issue by ChristianBesp** [SiLab-Bonn/beam_telescope_analysis#8]
Using reduce_events() on the merged data file throws the following error:
<pre>Traceback (most recent call last):
  File &quot;telescope.py&quot;, line 237, in &lt;module&gt;
    run_analysis(hit_files=hit_files)
  File &quot;telescope.py&quot;, line 144, in run_analysis
    max_events=500000)
  File &quot;/home/silab/git/beam_telescope_analysis/beam_telescope_analysis/tools/storage_utils.py&quot;, line 75, in wrapper
    ret_val = func(*args, **kwargs)
  File &quot;/home/silab/git/beam_telescope_analysis/beam_telescope_analysis/tools/data_selection.py&quot;, line 131, in reduce_events
    logging.info(&apos;Reducing events for node %s&apos;, node.name)
  File &quot;/home/silab/miniconda3/envs/bta/lib/python2.7/site-packages/tables/group.py&quot;, line 839, in __getattr__
    return self._f_get_child(name)
  File &quot;/home/silab/miniconda3/envs/bta/lib/python2.7/site-packages/tables/group.py&quot;, line 711, in _f_get_child
    self._g_check_has_child(childname)
  File &quot;/home/silab/miniconda3/envs/bta/lib/python2.7/site-packages/tables/group.py&quot;, line 398, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/arguments`` does not have a child named ``name``
</pre>

It should probabaly be checked if the node is a group and in that case just copy it.

**Comment by ChristianBesp** [comment]
This should already solve the issue (at least it does for me):
<pre>if type(node) == tb.group.Group:
    continue</pre>

**Comment by YannickDieter** [comment]
Fixed.
